kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: python:3.9
    commands:
      - pip install --no-cache-dir -r requirements.txt
      - pytest tests

  - name: build
    image: plugins/docker
    settings:
      repo: my-dockerhub-username/myapp
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      build_args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}

  - name: deploy
    image: plugins/docker
    settings:
      repo: my-dockerhub-username/myapp
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}
